### ISSUE TITLE
Code completion

### ISSUE THREAD

**Issue by dyigitpolat** [kriegalex/vscode-cudatools#1]
It would be great to have code completion (at least at a very basic level) in CUDA code.

**Comment by kriegalex** [comment]
Hello,
As you have seen, I've lost interest into this project since CLion started to support officially CUDA. Also, I'm not working daily with CUDA anymore. Sorry :(

Anyone is free to try to do it, but the task is gigantic. Maybe if someone knows how to build on top of the existing C++ Intellisense, otherwise...
