### ISSUE TITLE
any update?

### ISSUE THREAD

**Issue by tingxueronghua** [kriegalex/vscode-cudatools#2]
Will there be any update about this repository?  I really look forward to such tools making cuda code completion possible.

**Comment by kriegalex** [comment]
Hello,
As you have seen, I've lost interest into this project since CLion started to support officially CUDA. Also, I'm not working daily with CUDA anymore. Sorry :(

Anyone is free to try to do it, but the task is gigantic. Maybe if someone knows how to build on top of the existing C++ Intellisense, otherwise...
